import { escapeHtml } from '../components.js';

const conversations = [
  { id:'chat-001', name:'Maninder Singh', initials:'MS', preview:'It would be nice to learn more about each other.', time:'10:42 AM', unread:2, online:true, messages:[['them','Hello! Thanks for connecting.'],['me','Hi Maninder, nice to connect with you.'],['them','It would be nice to learn more about each other.']] },
  { id:'chat-002', name:'Jasleen Kaur', initials:'JK', preview:'Family introductions can happen when comfortable.', time:'Yesterday', unread:0, online:false, messages:[['them','Hello, hope you are doing well.'],['me','Yes, thank you!']] },
  { id:'chat-003', name:'Dr. Simran Dhillon', initials:'SD', preview:'Thank you for expressing interest.', time:'Mon', unread:0, online:false, messages:[['them','Thank you for expressing interest.']] }
];

export function renderChats({ toast } = {}) {
  const page=document.getElementById('page-chats');
  if(!page)return;
  page.innerHTML=`<div class="chat-layout"><section class="conversation-list"><div class="chat-heading"><p class="eyebrow">Connections</p><h1>Messages</h1></div><div id="conversationItems">${conversations.map(conversationItem).join('')}</div></section><section class="chat-window" id="chatWindow"><div class="chat-empty"><div class="empty-icon">💬</div><h2>Your conversations</h2><p>Select a connection to start a respectful conversation.</p></div></section></div>`;
  page.querySelectorAll('[data-conversation]').forEach(item=>item.addEventListener('click',()=>openConversation(item.dataset.conversation,toast)));
}
function conversationItem(c){return `<button class="conversation" data-conversation="${c.id}"><span class="chat-avatar">${escapeHtml(c.initials)}${c.online?'<i></i>':''}</span><span class="conversation-copy"><strong>${escapeHtml(c.name)}</strong><span>${escapeHtml(c.preview)}</span></span><span class="conversation-meta"><small>${escapeHtml(c.time)}</small>${c.unread?`<b>${c.unread}</b>`:''}</span></button>`;}
function openConversation(id,toast){const c=conversations.find(x=>x.id===id);if(!c)return;const windowEl=document.getElementById('chatWindow');windowEl.innerHTML=`<div class="chat-top"><button class="chat-back" type="button" id="chatBack">←</button><span class="chat-avatar">${escapeHtml(c.initials)}${c.online?'<i></i>':''}</span><div><strong>${escapeHtml(c.name)}</strong><small>${c.online?'Online':'Recently active'}</small></div><button class="chat-more" type="button" id="chatMore">⋯</button></div><div class="message-area" id="messageArea"><div class="date-separator">Today</div>${c.messages.map(message).join('')}</div><form class="composer" id="composer"><input id="messageInput" maxlength="500" autocomplete="off" placeholder="Write a respectful message…" aria-label="Message"><button type="submit" aria-label="Send message">➤</button></form><div class="chat-safety">🔒 Keep personal contact details private until you are comfortable.</div>`;windowEl.querySelector('#chatBack').addEventListener('click',()=>renderChats({toast}));windowEl.querySelector('#chatMore').addEventListener('click',()=>toast?.('Block and report controls will connect to moderation later'));windowEl.querySelector('#composer').addEventListener('submit',e=>{e.preventDefault();const input=e.currentTarget.querySelector('input');const value=input.value.trim();if(!value)return;document.getElementById('messageArea').insertAdjacentHTML('beforeend',message(['me',value]));input.value='';const area=document.getElementById('messageArea');area.scrollTop=area.scrollHeight;toast?.('Message sent');});windowEl.querySelector('#messageInput').focus();}
function message([from,text]){return `<div class="message-row ${from==='me'?'mine':'theirs'}"><div class="bubble">${escapeHtml(text)}<small>${from==='me'?'Sent':'Received'}</small></div></div>`;}
